package com.example.Student_Libriary_Management_System.Service;

import com.example.Student_Libriary_Management_System.Enums.CardStatus;
import com.example.Student_Libriary_Management_System.Models.Card;
import com.example.Student_Libriary_Management_System.Models.Student;
import com.example.Student_Libriary_Management_System.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;


    public String createStudent(Student student){

        //set card attributed that are not autogenerated
        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudent(student);


        //update the card in student attribute
        student.setCard(card);

        //in case this is unidirectional we need to save both parent(student) and child(card) seperately
        //since this is bidirectional we only need to save parent


        // only need to save student cascade will take care of card automatically
        studentRepository.save(student);


        return "Student added";
    }
}
